openapi: 3.0.0
info:
  title: Passenger API
  version: 1.0.0

paths:
  /passengers:
    get:
      summary: Get passengers by flight number and date
      tags:
        - Passengers
      parameters:
        - name: flightNumber
          in: query
          required: true
          schema:
            type: string
        - name: departureDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of passengers
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        passengerId:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                        bookingId:
                          type: string
